import { requireAdmin } from "@/lib/auth";
import { supabaseAdmin } from "@/lib/supabase";

export default async function HaulersPage(){
  await requireAdmin();
  const { data: haulers } = await supabaseAdmin.from("partner_haulers").select("*").order("created_at", {ascending:false});
  async function createHauler(formData: FormData){"use server"; await supabaseAdmin.from("partner_haulers").insert({ company_name:String(formData.get("company_name")), contact_name:String(formData.get("contact_name")), phone:String(formData.get("phone")), email:String(formData.get("email")), service_cities:String(formData.get("service_cities")).split(",").map(v=>v.trim()), dumpster_sizes_offered:String(formData.get("dumpster_sizes_offered")).split(",").map(v=>v.trim()), base_pricing:JSON.parse(String(formData.get("base_pricing")||"{}")), notes:String(formData.get("notes")||""), active: formData.get("active") === "on" }); }
  return <main className="mx-auto max-w-5xl space-y-4 px-4 py-8"><form action={createHauler} className="card grid gap-2 md:grid-cols-2"><input name="company_name" className="rounded border p-2" placeholder="Company name"/><input name="contact_name" className="rounded border p-2" placeholder="Contact name"/><input name="phone" className="rounded border p-2" placeholder="Phone"/><input name="email" className="rounded border p-2" placeholder="Email"/><input name="service_cities" className="rounded border p-2" placeholder="Service cities (comma-separated)"/><input name="dumpster_sizes_offered" className="rounded border p-2" placeholder="Sizes (comma-separated)"/><input name="base_pricing" className="rounded border p-2" placeholder='{"10 yd":350}'/><textarea name="notes" className="rounded border p-2" placeholder="Notes"/><label><input type="checkbox" name="active" defaultChecked/> Active</label><button className="rounded bg-brand-500 p-2 text-white">Add Hauler</button></form><div className="card overflow-x-auto"><table className="w-full text-sm"><thead><tr><th>Company</th><th>Cities</th><th>Sizes</th><th>Active</th></tr></thead><tbody>{haulers?.map((h)=><tr key={h.id} className="border-t"><td>{h.company_name}</td><td>{h.service_cities?.join(", ")}</td><td>{h.dumpster_sizes_offered?.join(", ")}</td><td>{h.active ? "Yes":"No"}</td></tr>)}</tbody></table></div></main>
}
